import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactQueryProvider } from '@/components/ReactQuery';
import './globals.css'
import { SearchBar } from '@/components/SearchBar';
import { Navigation } from '@/components/Navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <header className="flex justify-center sm:p-4">
            <SearchBar />
          </header>
          <main className="container mx-auto md:px-24">
            {children}
          </main>
          <Navigation />
        </ReactQueryProvider>
      </body>
    </html>
  )
}
